### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by dbaldoni** [nextcloud/user_sql#34] opened 2018-05-16 15:22 UTC
Hi, I tried to install the plugin but I get a warning:
Error: This app can not be enabled because it makes the server unstable
Then tried to enable it with the command occ enable:app user_sql
App gets enabled but return server error 500. had to uninstall it.

Running Nextcloud 13 and Php7.2

**Comment by mlojewski-me** [comment] 2018-05-16 15:26
I guess it was caused by an uncaught exception.
Are you able to give us logs from that event (nextcloud and php)?

**Comment by dbaldoni** [comment] 2018-05-16 15:52
Nextcloud log
`require_once(/var/www/html/terrabox/apps/user_sql/appinfo/../lib/group_sql.php): failed to open stream: No such file or directory at /var/www/html/terrabox/apps/user_sql/appinfo/app.php#25`

`require_once(): Failed opening required '/var/www/html/terrabox/apps/user_sql/appinfo/../lib/group_sql.php' (include_path='/var/www/html/terrabox/3rdparty/pear/console_getopt:/var/www/html/terrabox/3rdparty/pear/pear_exception:/var/www/html/terrabox/3rdparty/pear/pear-core-minimal/src:/var/www/html/terrabox/3rdparty/pear/archive_tar:/var/www/html/terrabox/apps') at /var/www/html/terrabox/apps/user_sql/appinfo/app.php#25`

PHP
`[php7:error] [pid 3245] [client 93.64.157.26:54632] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/terrabox/apps/user_sql/appinfo/../lib/group_sql.php' (include_path='/var/www/html/terrabox/3rdparty/pear/console_getopt:/var/www/html/terrabox/3rdparty/pear/pear_exception:/var/www/html/terrabox/3rdparty/pear/pear-core-minimal/src:/var/www/html/terrabox/3rdparty/pear/archive_tar:/var/www/html/terrabox/apps') in /var/www/html/terrabox/apps/user_sql/appinfo/app.php on line 25`

**Comment by ed-wart** [comment] 2018-05-26 10:11
I'm having the same issue, nextcloud stating that "Error: This app can not be enabled because it makes the server unstable"

**Comment by gpgmailencrypt** [comment] 2018-05-26 15:29
Does the file "YOUR_NEXTCLOUD_INSTALLATION_DIR"/apps/user_sql/appinfo/lib/group_sql.php exist on your system?

**Comment by Ko-** [comment] 2018-05-30 10:59
7649d230529ba390a54ba21d0c9808ce75c51cd3 broke this by renaming `group_sql.php` to `$rows = $this -> helper -> runQuery('getGroupUsers', array('gid' =>`.

**Comment by mlojewski-me** [comment] 2018-05-31 09:10
Merged.

**Closed by mlojewski-me** 2018-05-31 09:10 UTC
